#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

APP="$1"; verify_app_name "$APP"
IMAGE_TAG="$(get_running_image_tag "$APP")"
IMAGE=$(get_app_image_name "$APP" "$IMAGE_TAG")
DEST="/etc/cron.d/$APP"

echo "-----> Copying CRON file content to /etc/cron.d/$APP"
copy_from_image "$IMAGE" "CRON" "$DEST" 2>/dev/null || true
